[package]
name = "telemetry_client"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "High-performance telemetry client for system monitoring"

[dependencies]
sysinfo.workspace = true
