[package]
name = "telemetry_server"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "High-performance telemetry server for real-time monitoring"

[dependencies]
serde.workspace = true
serde_json.workspace = true
